config/routes.rb
Rails.application.routes.draw do
  resources :dads
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dad.rb
class Dad < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/dads_controller.rb
class DadsController < ApplicationController
  before_action :set_dad, only: [:show, :edit, :update, :destroy]

  # GET /dads
  # GET /dads.json
  def index
    @dads = Dad.all
  end

  # GET /dads/1
  # GET /dads/1.json
  def show
  end

  # GET /dads/new
  def new
    @dad = Dad.new
  end

  # GET /dads/1/edit
  def edit
  end

  # POST /dads
  # POST /dads.json
  def create
    @dad = Dad.new(dad_params)

    respond_to do |format|
      if @dad.save
        format.html { redirect_to @dad, notice: 'Dad was successfully created.' }
        format.json { render :show, status: :created, location: @dad }
      else
        format.html { render :new }
        format.json { render json: @dad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dads/1
  # PATCH/PUT /dads/1.json
  def update
    respond_to do |format|
      if @dad.update(dad_params)
        format.html { redirect_to @dad, notice: 'Dad was successfully updated.' }
        format.json { render :show, status: :ok, location: @dad }
      else
        format.html { render :edit }
        format.json { render json: @dad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dads/1
  # DELETE /dads/1.json
  def destroy
    @dad.destroy
    respond_to do |format|
      format.html { redirect_to dads_url, notice: 'Dad was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dad
      @dad = Dad.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dad_params
      params.permit(:name, :rating)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dads_helper.rb
module DadsHelper
end

app/views/dads/_form.html.erb
<%= form_with(model: @dad, local: true) do |form| %>
  <div class="form-group">
    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name, id: :dad_name, class: "form-control", placeholder: "Name this dad", autofocus: true %>
    </div>

    <div class="field">
      <%= form.label :rating %>
      <%= form.text_field :rating, id: :dad_rating, class: "form-control" %>
    </div>

    <div class="btn-grtnoup actions">
      <%= form.submit "Save", class: "btn btn-success", id: "save-new-project" %>
      <%= button_tag "Cancel", :type => 'button', class: "btn tbn-default", id: "cancel-new-project" %>
    </div>
  </div>
<% end %>

app/views/dads/edit.html.erb
<h1>Editing Dad</h1>

<%= render 'form', dad: @dad %>

<%= link_to 'Show', @dad %> |
<%= link_to 'Back', dads_path %>

app/views/dads/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Dads</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Rating</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dads.each do |dad| %>
      <tr>
        <td><%= dad.name %></td>
        <td><%= dad.rating %></td>
        <td><%= link_to 'Show', dad %></td>
        <td><%= link_to 'Edit', edit_dad_path(dad) %></td>
        <td><%= link_to 'Destroy', dad, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dad', new_dad_path %>


<%= render "layouts/projects_section.html" %>

app/views/dads/new.html.erb
<h1>New Dad</h1>

<%= render 'form', dad: @dad %>

<%= link_to 'Back', dads_path %>

app/views/dads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @dad.name %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @dad.rating %>
</p>

<%= link_to 'Edit', edit_dad_path(@dad) %> |
<%= link_to 'Back', dads_path %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
    <!-- nav bar header -->
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="#">Moignard</a>
        </div>
    
    <!-- navbar navagation items -->
        <ul class="nav navbar-nav">
            <li><a href="#">Home</a></li>
            <li><a href="#">Page 2</a></li>
            <li><a href="#">Page 3</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li>
                <a href="#">
                    <span class="glyphicon glyphicon-user"></span> Sign Up
                </a>
            </li>
            <li>
                <a href="#">
                    <span class="glyphicon glyphicon-log-in"></span> Login
                </a>
            </li>
        </ul>
    </div>
</nav>

app/views/layouts/_projects_section.html.erb
<main class="container home">
    <div class="justify-content-start row page-header">
        <div class=" page-header-inline">
            <h4>Projects</h4>
        </div>
        <div class="page-header-inline f-right">
            <div class="btn-group">
                <button class="btn btn-primary" id="new-project-button">New</button>
                <button class="btn btn-default">...</button>
            </div>

            <div id="new-project-dropdown" class="dropdown is-hidden">
                <%= render "dads/form.html"%>

            </div>
        </div>
        

        
    </div>

    <div id="projects-section" class="row">
        <% @dads.each do |p| %>
            <div class="col-md-4">
                <a href="#" class="project-card">
                    
                    <h2><%= p.name %></h2>
                    <p><%= p.rating %></p>
                    <%= link_to "Delete", dads_path(p), method: :delete, data: { confirm: "Are you sure?" }%>
                    <%= link_to 'Edit', edit_dad_path(p) %>
                </a>
            </div>
        <% end %>
    </div>


</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dads</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"> 

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navbar.html" %>
    <%= yield %>
  </body>
</html>